language: node_js
node_js:
  - "4.1"
install:
  - npm install
  - bower install
before_deploy:
  - gulp release
  - cd releases/tv-show-reminder/win64
  - ls
deploy:
  skip_cleanup: true
branches:
  only:
    - develop